/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jML2M;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage primaryStage) throws Exception {
        Parent parent = FXMLLoader.load(getClass().getResource("/sample.fxml"));
        primaryStage.setScene(new Scene(parent));
        primaryStage.setTitle("Java with DI");
        primaryStage.show();
    }

    public static void main(String[] args) {
        App.launch(args);
    }
}
