/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jML2M;

import jML2M.controllers.HomeController;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage primaryStage) throws Exception {
        HomeController.create(primaryStage);
    }

    public static void main(String[] args) {
        App.launch(args);
    }
}
